export const bookHouseProjectColumns = [
    {
        name: 'projectId',
        required: true,
        label: '活动编号',
        align: 'center',
        field: 'projectId',
        miniCardHaveLabel: true,
    },
    {
        name: 'projectName',
        required: false,
        label: '活动名称',
        align: 'center',
        field: 'projectName',
        miniCardHaveLabel: false,
    },
    {
        name: 'houseSum',
        required: false,
        label: '活动房源',
        align: 'center',
        field: 'houseSum',
        miniCardHaveLabel: true,
    },
    {
        name: 'personSum',
        required: false,
        label: '活动租客',
        align: 'center',
        field: 'personSum',
        miniCardHaveLabel: true,
    },
    {
        name: 'projectProcessStatusName',
        required: false,
        label: '进行状态',
        align: 'center',
        field: 'projectProcessStatusName',
        miniCardHaveLabel: false,
        miniCardSite: "subscript",
    },
    {
        name: 'projectStatusName',
        required: false,
        label: '上架状态',
        align: 'center',
        field: 'projectStatusName',
        miniCardHaveLabel: true,
    },
    {
        name: 'createUserName',
        required: false,
        label: '创建人',
        align: 'center',
        field: 'createUserName',
        miniCardHaveLabel: false,
        miniCardSite: "footerLeft",
    },
    {
        name: 'createTime',
        required: false,
        label: '创建时间',
        align: 'center',
        field: 'createTime',
        miniCardHaveLabel: false,
        miniCardSite: "footerRight",
    },
    {
        name: 'operation',
        required: false,
        label: '操作',
        align: 'center',
        field: 'operation',
        miniCardHaveLabel: false,
    },
]


export const bookHouseOrderColumns = [
    {
        name: 'projectHouseOrderId',
        required: true,
        label: '订单编号',
        align: 'center',
        field: 'projectHouseOrderId',
        miniCardHaveLabel: true,
    },
    {
        name: 'projectId',
        required: true,
        label: '活动编号',
        align: 'center',
        field: 'projectId',
        miniCardHaveLabel: true,
    },
    {
        name: 'projectName',
        required: false,
        label: '活动名称',
        align: 'center',
        field: 'projectName',
        miniCardHaveLabel: true,
    },
    {
        name: 'projectHouseId',
        required: false,
        label: '房源编号',
        align: 'center',
        field: 'projectHouseId',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseAddress',
        required: false,
        label: '房源信息',
        align: 'center',
        field: 'houseAddress',
        miniCardHaveLabel: false,
    },
    {
        name: 'bookUserName',
        required: false,
        label: '姓名',
        align: 'center',
        field: 'bookUserName',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookUserPhone',
        required: false,
        label: '手机号',
        align: 'center',
        field: 'bookUserPhone',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookUserIdCard',
        required: false,
        label: '身份证号',
        align: 'center',
        field: 'bookUserIdCard',
        miniCardHaveLabel: true,
    },
    {
        name: 'orderStatusName',
        required: false,
        label: '订单状态',
        align: 'center',
        field: 'orderStatusName',
        miniCardHaveLabel: false,
        miniCardSite: "subscript",
    },
    {
        name: 'createTime',
        required: false,
        label: '创建时间',
        align: 'center',
        field: 'createTime',
        miniCardHaveLabel: false,
        miniCardSite: "footerRight",
    },
]


export const bookUserColumns = [
    {
        name: 'bookOrder',
        required: true,
        label: '选房顺序',
        align: 'center',
        field: 'bookOrder',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookUserName',
        required: true,
        label: '姓名',
        align: 'center',
        field: 'bookUserName',
        miniCardHaveLabel: false,
    },
    {
        name: 'bookUserPhone',
        required: false,
        label: '手机号',
        align: 'center',
        field: 'bookUserPhone',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookUserIdCard',
        required: false,
        label: '身份证号',
        align: 'center',
        field: 'bookUserIdCard',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookMailStatusName',
        required: false,
        label: '短信发送状态',
        align: 'center',
        field: 'bookMailStatusName',
        miniCardHaveLabel: true,
    },
    {
        name: 'bookTeamStatusName',
        required: false,
        label: '组队状态',
        align: 'center',
        field: 'bookTeamStatusName',
        miniCardHaveLabel: false,
        miniCardSite: "subscript",
    },
    {
        name: 'bookUserRealStartTime',
        required: false,
        label: '选房起始时间',
        align: 'center',
        field: 'bookUserRealStartTime',
        miniCardHaveLabel: true,
    },
    {
        name: 'operation',
        required: false,
        label: '操作',
        align: 'center',
        field: 'operation',
        style: 'color: #027BE3;cursor: pointer',
    },
]

export const bookHouseColumns = [
    {
        name: 'projectHouseId',
        required: true,
        label: '房源编号',
        align: 'center',
        field: 'projectHouseId',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseProjectName',
        required: true,
        label: '项目名称',
        align: 'center',
        field: 'houseProjectName',
        miniCardHaveLabel: true,
    },
    {
        name: 'divisionName',
        required: false,
        label: '所在区域',
        align: 'center',
        field: 'divisionName',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseAddress',
        required: false,
        label: '房源信息',
        align: 'center',
        field: 'houseAddress',
        miniCardHaveLabel: false,
    },
    {
        name: 'rentStyle',
        required: false,
        label: '租赁方式',
        align: 'center',
        field: 'rentStyle',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseModel',
        required: false,
        label: '房型',
        align: 'center',
        field: 'houseModel',
        miniCardHaveLabel: true,
    },
    {
        name: 'orientation',
        required: false,
        label: '朝向',
        align: 'center',
        field: 'orientation',
        miniCardHaveLabel: true,
    },
    {
        name: 'area',
        required: false,
        label: '面积',
        align: 'center',
        field: 'area',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseFloor',
        required: false,
        label: '楼层',
        align: 'center',
        field: 'houseFloor',
        miniCardHaveLabel: true,
    },
    {
        name: 'rentalCharge',
        required: false,
        label: '租金',
        align: 'center',
        field: 'rentalCharge',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseBookStatusName',
        required: false,
        label: '房源选择状态',
        align: 'center',
        field: 'houseBookStatusName',
        miniCardHaveLabel: false,
        miniCardSite: "subscript",
    },
    {
        name: 'operation',
        required: false,
        label: '操作',
        align: 'center',
        field: 'operation',
        style: 'color: #027BE3;cursor: pointer',
    },
]

export const importHouseProjectColumns = [
    {
        name: 'houseProjectId',
        required: true,
        label: '项目编号',
        align: 'center',
        field: 'houseProjectId',
        miniCardHaveLabel: true,
    },
    {
        name: 'houseProjectName',
        required: true,
        label: '项目名称',
        align: 'center',
        field: 'houseProjectName',
        miniCardHaveLabel: false,
    },
    {
        name: 'houseProjectNum',
        required: true,
        label: '可关联房源',
        align: 'center',
        field: 'houseProjectNum',
        miniCardHaveLabel: true,
    },
    {
        name: 'operation',
        required: true,
        label: '操作',
        align: 'center',
        field: 'operation',
        style: 'color: #027BE3;cursor: pointer',
    },
]